version: "3"
services:
  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    ports:
      - ${API_PORT:-3000}:3000
    networks:
      - net

  db:
    image: mysql:latest
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./docker/db/data/${DB_NAME}:/docker-entrypoint-initdb.d
    networks:
      - net

networks:
  net:
