version: "3"
services:
  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    ports:
      - ${API_PORT:-3000}:3000
    networks:
      - net

  db:
    image: ${DB_TYPE}:latest
    ports:
      - ${DB_PORT:-4000}:${DB_INNER_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-1234}
      - POSTGRES_PASSWORD=${DB_PASS:-1234}
    volumes:
      - ./docker/db/${DB}/initdb:/docker-entrypoint-initdb.d
    networks:
      - net

networks:
  net:
