name:                nlidb-bo
version:             0.0.1
license:             Propietary
author:              "César González"
maintainer:          "ceguel@gmail.com"
copyright:           "2019 César González"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/nlidb-bo#readme>

dependencies:
  - base                  >= 4.7       && <  5
  - megaparsec            >= 7.0.0     && <  8.0
  - aeson                 >= 1.0       && <= 1.5
  - bytestring            >= 0.10.4    && <  0.11
  - text                  >= 1.2.3.0   && <  1.3
  - containers            >= 0.4.2.1   && <  0.7
  - unordered-containers  >= 0.2.8.0   && <  0.3
  - transformers          >= 0.3.0.0   && <  0.6
  - scientific            >= 0.3.6.2   && <  0.4
  - vector                >= 0.12.0.1  && <  0.13
  - mtl                   >= 2.0       && <= 2.2.2
  - websockets            >= 0.11.0    && <= 0.12.5.3
  - wai-websockets        >= 1.0       && <= 3.5
  - uuid                  >= 1.0       && <= 1.4
  - morpheus-graphql      == 0.1.1
  - HDBC                  >= 2.4       && <= 3
  - HDBC-odbc             >= 2.6       && <= 3

library:
  source-dirs:          src
  exposed-modules:
    - Mythology.API
  ghc-options:
    - -Wall

executables:
  nlidb-bo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - base >= 4.7 && < 5
      - scotty
      - aeson
      - bytestring
      - mtl
      - text
      - wai
      - warp
      - morpheus-graphql
      - HDBC
      - nlidb-bo

tests:
  nlidb-bo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies: []
