name:                nlidb-bo
version:             0.0.1
license:             AllRightsReserved
author:              "César González"
maintainer:          "ceguel@gmail.com"
copyright:           "2019 César González"

extra-source-files:
  - Readme.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/nlidb-bo#readme>

dependencies:
  - base                  >= 4.7       && <  5
  - bytestring            >= 0.10.4    && <  0.11
  - text                  >= 1.2.3     && <  1.3
  - aeson                 >= 1.0       && <= 1.5
  - dotenv                >= 0.8       && <= 1
  - morpheus-graphql      >= 0.2       && <  0.3
  - HDBC                  >= 2.4       && <  3
  - HDBC-odbc             >= 2.6       && <  3

default-extensions: OverloadedStrings

library:
  source-dirs: src
  exposed-modules:
    - GraphQL.API
  ghc-options:
    - -Wall

executables:
  nlidb-bo-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - scotty
      - nlidb-bo

tests:
  nlidb-bo-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies: []
